### ISSUE TITLE
Adicionar detalhes ao README, parte db

### ISSUE THREAD

**Issue by gabrielfior** [CovidZero/hummingbird-v2#20]
Sugestao: adicionar mais detalhes relacionados a iniciar o db (init), bem como ao migrate, detalhando onde os comandos devem ser executados e o que acontece com cada parte.
Penso que assim ficaria mais simples para novas pessoas contribuirem para o projeto.

Valeu!

**Comment by evertoncastro** [comment]
Muito bom @gabrielfior. Vamos fazer isso sim. hoje no call das 20:00 vamos falar sobre documentação tbm. Valeu
