### ISSUE TITLE
[Sugestao] Mudancas datamodel

### ISSUE THREAD

**Issue by gabrielfior** [CovidZero/hummingbird-v2#21]
Checando os modelos no arquivo models.py, existem classes especificas para breakdown de casos para possiveis endpoints, e.g. casosPorEstado, casosPorCidade:

```python
class City(db.Model):
    __tablename__ = 'CITY'
    city = db.Column(db.String(255), primary_key=True)
```

```python
class State(db.Model):
    __tablename__ = 'STATE'
    state = db.Column(db.String(255), primary_key=True)
    country = db.Column(db.String(255), nullable=False)
    total_cases = db.Column(db.Integer)
```

Uma outra possibilidade seria criar um Model apenas para Casos, por ex:
```python
class CasesEntry(db.Model):
    __tablename__ = 'CASES_ENTRIES'
    id = db.Column(db.String(255), primary_key=True)
    date = db.Column(db.DateTime, nullable=False)
    new_cases = db.Column(db.Integer)
    total_cases = db.Column(db.Integer)
    city = db.Column(db.String(255), nullable=False)
    state = db.Column(db.String(255), nullable=False)
    country = db.Column(db.String(255), primary_key=True)
```

Dessa forma, bastaria uma unica tabela para todas as informacoes relacionadas a casos, e a partir dela todos os filtros relacionados a cidade, estado e pais poderiam ser construidas.
Fica a sugestao.
Valeu!

**Comment by nizbel** [comment]
Isso deve ser visto com o @jeduardo824 , fiz esses models de acordo com as estruturas de tabelas que ele passou. A ideia era guardar a evolução diária por estado, e para cidades guardarmos apenas a informação mais atual.

**Comment by evertoncastro** [comment]
@gabrielfior, pelo que entendemos já existe uma base de dados modelada por outra equipe. neste caso dessa API estamos apenas mapeando com as models uma estrutura que já existe. Hoje no call vamos dar uma repassada no modelo para vermos como estamos.

**Comment by gabrielfior** [comment]
Entendi! Obrigado
