### ISSUE TITLE
Criar arquivo com diretrizes sobre contribuição no CONTRIBUTING.MD

### ISSUE THREAD

**Issue by evertoncastro** [CovidZero/hummingbird-v2#31]
Tipo o README.md mas chamado CONTRIBUTING.MD e falando as guidelines que seguimos para contribuições como Branchs, PRs e etc!

**Comment by evertoncastro** [comment]
- Ser mais descritivo no nome do PR
- Seguir Padrões de Segurança ao desenvolver

**Comment by jeduardo824** [comment]
Arquivo criado, faltando adicionar o conteudo
