### ISSUE TITLE
Modelar tabela city

### ISSUE THREAD

**Issue by evertoncastro** [CovidZero/hummingbird-v2#67]
Devemos mudar a modelagem do model City para serem correspondentes a esses campos: 

CREATE TABLE public.city (
	id serial NOT NULL,
	country varchar NULL,
	state varchar NULL,
	city varchar NULL,
	totalcases int4 NULL,
	CONSTRAINT city_pkey PRIMARY KEY (id)
);
**APENAS EXEMPLO - ESSES CAMPOS DEVEM IR PARA AS MODELS DO SQLALCHEMY**

Também temos que alterar a `__TABLENAME___` para `city`, em minuscula.

Vocês podem rodar esse Script not banco de vocês para testar a funcionalidade!

**Comment by jeduardo824** [comment]
Fechando após PR com conflitos. Resolvido em #93
