### ISSUE TITLE
Configurar CORS

### ISSUE THREAD

**Issue by jeduardo824** [CovidZero/hummingbird-v2#92]
Nós precisamos configurar politicas de CORS para que o fronted consiga acessar nossa API externamente sem ser bloqueado pelo navegador.

Acho que a melhor opção para usarmos: https://flask-cors.readthedocs.io/en/latest/

**Comment by nizbel** [comment]
Parece bom, usaríamos o modo geral que é mostrado em **Simple Usage**?

**Comment by jeduardo824** [comment]
Isso aí!! Closed by #93
